### ISSUE TITLE
looking forward to this :)

### ISSUE THREAD

**Issue by couleurm** [simplePCBuilding/FSRImageVideoUpscalerFrontend#1]

**Comment by janishutz** [comment]
I am right now working on it. Will first probably be available on Linux only, but soon after for Windows as well.

**Comment by couleurm** [comment]
I can help with making a [scoop](http://scoop.sh) manifest 👍

**Comment by janishutz** [comment]
Ohh sure that'd help a lot... I'll be compiling it using PyInstaller through Wine for Windows probably.

**Comment by janishutz** [comment]
Also the Windows version will need slightly modified code.

**Comment by janishutz** [comment]
The Windows version has been implemented directly into the same file as the Linux version. Probably, I'll add support for macOS at another point.

**Comment by janishutz** [comment]
@couleurm It's now working fully, on both Linux and Windows
