### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by halfcyan** [simplePCBuilding/FSRImageVideoUpscalerFrontend#10]
Hello! I love this project, so I'd like to see if I can help get it running on Windows. As I understand it, you'll have to finish the migration to PyQT beforehand, but once that is finished, I can see if any tweaks need to be done for Windows.

**Comment by janishutz** [comment]
So far, I have created a CLI utility that runs on all major OS platforms and I have started working on PyQT5 migration. As I have other projects I need to work on, this takes some time and I am troubleshooting some kinda odd bugs currently with somebody. If you have any suggestions for any other upscaling library to include, do let us know

**Comment by halfcyan** [comment]
The only things I managed to find were custom PyTorch implementations to be honest

**Comment by janishutz** [comment]
I have chosen to abandon the PyQt5 GUI and instead started working on an Electron App, to make it look so much better

**Comment by janishutz** [comment]
I have made some significant progress on the GUI, but it’ll still take some time to complete.

**Comment by janishutz** [comment]
@halfcyan The Windows version has now been released, including a GUI that is written in Electron

**Comment by halfcyan** [comment]
Wow I guess things move fast in the summer! I'll check it out.
