### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by janishutz** [simplePCBuilding/FSRImageVideoUpscalerFrontend#16]
This project still lacks a great name and therefore a new and way nicer logo as well. Please comment on this issue if you have any suggestions. I will add a link to this here in the README.md file

**Comment by couleurm** [comment]
FSRVidScaler (FVS)

**Comment by janishutz** [comment]
Hhm... really don't know since I do wanna drop FSR from the name, since the project now is way more than just a FSR frontend

**Comment by couleurm** [comment]
SimpleMediaUpscaler (SMU)

**Comment by janishutz** [comment]
We've decided to go with smuL (SimpleMediaUpscalerLite), because funny

**Comment by ThatPlasma** [comment]
smuL (pronounced small cause UPscaler)

**Comment by couleurm** [comment]
is a smul video tool 😇
