### ISSUE TITLE
ffmpeg not integratable into repo

### ISSUE THREAD

**Issue by janishutz** [simplePCBuilding/FSRImageVideoUpscalerFrontend#3]
I will be adding a download-script for ffmpeg in a future version of the app. Currently you'll need to add it manually.

**Comment by couleurm** [comment]
it's dead easy on any linux system with a package manager

same on windows with scoop

**Comment by janishutz** [comment]
Yeah I knew about Linux lol... there I'll just add it as dependency in the pkgbuild for Arch and when trying to get into the official repos of the other distros

**Comment by janishutz** [comment]
ohh... well I just realised... I'll use the installer to automatically install ffmpeg on Windows if you download the installer and for Linux I'll create a bash-script and, if I am able to publish the app on the official repos, I'll set it as dependency

**Comment by janishutz** [comment]
I've added a guide to the wiki on how to install it.
